# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-01-21 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0028_auto_20180606_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcategory',
            name='name_el',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='description_el',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='title_el',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
    ]
