# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-01-21 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_auto_20190629_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='description_el',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backup',
            name='name_el',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='description_el',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='license_text_el',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='name_el',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='name_el',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restrictioncodetype',
            name='description_el',
            field=models.TextField(editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restrictioncodetype',
            name='gn_description_el',
            field=models.TextField(max_length=255, null=True, verbose_name=b'GeoNode description'),
        ),
        migrations.AddField(
            model_name='spatialrepresentationtype',
            name='description_el',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spatialrepresentationtype',
            name='gn_description_el',
            field=models.CharField(max_length=255, null=True, verbose_name=b'GeoNode description'),
        ),
        migrations.AddField(
            model_name='topiccategory',
            name='description_el',
            field=models.TextField(default=b'', null=True),
        ),
        migrations.AddField(
            model_name='topiccategory',
            name='gn_description_el',
            field=models.TextField(default=b'', null=True, verbose_name=b'GeoNode description'),
        ),
    ]
