# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-01-21 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0032_auto_20190625_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='abstract_el',
            field=models.TextField(blank=True, help_text='brief narrative summary of the content of the resource(s)', max_length=2000, null=True, verbose_name='abstract'),
        ),
        migrations.AddField(
            model_name='map',
            name='constraints_other_el',
            field=models.TextField(blank=True, help_text='other restrictions and legal prerequisites for accessing and using the resource or metadata', null=True, verbose_name='restrictions other'),
        ),
        migrations.AddField(
            model_name='map',
            name='data_quality_statement_el',
            field=models.TextField(blank=True, help_text="general explanation of the data producer's knowledge about the lineage of a dataset", max_length=2000, null=True, verbose_name='data quality statement'),
        ),
        migrations.AddField(
            model_name='map',
            name='purpose_el',
            field=models.TextField(blank=True, help_text='summary of the intentions with which the resource(s) was developed', max_length=500, null=True, verbose_name='purpose'),
        ),
        migrations.AddField(
            model_name='map',
            name='supplemental_information_el',
            field=models.TextField(default='No information provided', help_text='any other descriptive information about the dataset', max_length=2000, null=True, verbose_name='supplemental information'),
        ),
        migrations.AddField(
            model_name='map',
            name='title_el',
            field=models.CharField(help_text='name by which the cited resource is known', max_length=255, null=True, verbose_name='title'),
        ),
    ]
